name: dkhfst

services: 
  # ---------------
  # DNSMasq Service
  # ---------------
  dns: 
    container_name: dkhfst-dns
    build: 
      context: ./dnsmasq
      dockerfile: Dockerfile 
    restart: always 
    volumes: 
      - ../../../data/dns/:/etc/dnsmasq.d/
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks: 
      net:  
        ipv4_address: 172.20.0.2   

  # -------------
  # Caddy Service
  # -------------
  caddy: 
    container_name: dkhfst-caddy 
    build: 
      context: ./caddy 
      dockerfile: Dockerfile 
    restart: always 
    volumes: 
      - caddy-config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/start.sh:/home/caddy/start.sh
      - dkhfst-caddy-data:/data/caddy
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sh /home/caddy/start.sh
    networks: 
      - net
       

# -------
# VOLUMES 
# -------
volumes:
  dkhfst-caddy-data: 
    external: true 
  caddy-config: 
    driver: local

# --------
# NETWORKS 
# --------
networks: 
  net: 
    name: dkhfst-net
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24  
          gateway: 172.20.0.1